### ISSUE TITLE
Infer treaty lineage from treaty title/text

### ISSUE THREAD

**Issue by jhollway** [globalgov/manyenviron#43]

**Comment by henriquesposito** [comment]
If lineages are a combination of activity and area, what is an area and what is an activity?

Areas need be not too small that they not become redundant (i.e. country) and not too big they not become too broad (i.e. continent). Then, which (sub)regions should we include? 

The same is true for activity. For dealing with a broad range of treaties across several domains we might need to code activities not too specific, but also not too broad... What is an activity then? Perhaps we can start with actions (verbs) for activities?

@EstherPeev could you please compile a list of how this is done in GNEVAR and elsewhere so that we can start to put together a dictionary for the function to code agreement titles and text upon? Thank you.

**Comment by EstherPeev** [comment]
Here is a rough summary of how areas and targets have been categorized in GNEVAR and last column (action) is the categories used for code_actions():
[https://app.zenhub.com/files/326714201/6d951fbd-7d03-4d52-825a-ef3c819f58f6/download](https://app.zenhub.com/files/326714201/6d951fbd-7d03-4d52-825a-ef3c819f58f6/download)

As you can see, areas are quite precise, but we might want to group them by (sub)regions which could allow the user to decide whether to select very precise areas (like river or specific country) or very large areas (country or regions), and an activity (fishing, delimiting, etc).

**Comment by jhollway** [comment]
The challenge is that if you don't categorise areas based on some kind of named entity recognition, but on (sub)regions, then we would need some kind of geographical lookup or hierarchical clustering of geographic features.

**Comment by henriquesposito** [comment]
@jhollway Thank you for the feedback. We can, for example, use named entity recognition to extract country names or other entities from titles fairly easy with some wrapper packages/functions for openNLP available on GitHub (this gets a bit more verbose/complex when using `{openNLP}` or `{spacyr}` directly, but still fairly easy).

`remotes::install_github("trinker/entity")
code_area <- function(title) {
  out <- entity::location_entity(title)
  out
}
title <- head(qEnviron::agreements$IEADB$Title)
code_area(title)`

However, all the options using named entity recognition I know use external libraries and depend on JAVA/Python. NLP uses in general also require a model package, as the English language models package, which are not offered on CRAN anymore but on another repo (https://datacube.wu.ac.at/src/contrib/)...

However, I do find the name entity recognition a good approach to identifying various entities and then coding hierarchically from there (this can also become an extra argument for code_lineages()). I will keep on looking into it and try to find a better solution to use it programmatically.
